import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '../../components/SideBar'
import Login from "../../components/Login";
import { SessionProvider } from "../../components/SessionProvider"
import { getServerSession } from "next-auth";
import { authOptions } from '../../pages/api/auth/[...nextauth]';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by Samuel Bamigboye in 2023',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  const session = await getServerSession(authOptions)
  
  console.log(session);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ClientProvider */}
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): (
            <div className='flex'>
              
          <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem] text-white'> 
          <SideBar />
          </div>
          {/* ClientProvider - Notification*/}
        
          <div className='bg-[#343541] flex-1 '>{children} </div>
        </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
